description: >
  This command injects your foundation environment into the current $BASH_ENV

parameters:
  api_key:
    type: string
    description: Your Foundation Api-Key

steps:
  - run:
      environment:
        FOUNDATION_API_KEY: <<parameters.api_key>>
        FOUNDATION_API_URL: https://foundation-api.beta.teleology.io
      name: Foundation - Exporting Environment
      command: <<include(scripts/environment.sh)>>
  - store_artifacts:
      path: /tmp/.env
      destination: .env
  - run:
      name: Foundation - Setting Environment
      command: source /tmp/.env
