description: >
  This command injects your foundation environment into the current $BASH_ENV

parameters:
  api_key:
    type: string
    description: Your Foundation Api-Key

steps:
  - run:
      environment:
        FOUNDATION_API_KEY: <<parameters.api_key>>
      name: Foundation - Exporting Environment
      command: |
        curl -s https://raw.githubusercontent.com/teleology-io/foundation-cli/master/download.sh | bash
        ./foundation environment >> "$BASH_ENV"
        source "$BASH_ENV"
